<?php

namespace CrCms\Passport\Tests;

trait ApplicationTrait
{

    public static $app;
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        static::$app = require_once __DIR__.'/./bootstrap.php';
    }

    public static function tearDownAfterClass()
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub

        static::$app = null;
    }
}